name: Check typescript synthax
run-name: ${{ github.actor }} is testing the code base ⚙
on:
  push:
    branches:
      - main
      - develop

jobs:
 test_typescript:
    name: Test typescript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: ./package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run tsc
